import React from 'react';

const MarianoPerezPage: React.FC = () => {
    return (
        <>
            <h1 className="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-500 via-rose-600 to-amber-400 mb-2 tracking-tight">
                Mariano dit "Manuel" Perez, Maire de Zuhérois, enfant de la guerre
            </h1>

            <figure className="my-8">
                <img 
                    src="https://scontent-cdg4-1.xx.fbcdn.net/v/t39.30808-6/576374200_2240708019744747_3629281447584514383_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=127cfc&_nc_ohc=sWn_qj_1J58Q7kNvwFcML6N&_nc_oc=Adlci-6CMeUoaztCX_CTfTJEc6B8dXhtlGqc5THxDdKItxxecTCIWAVCKGuuMnQSvVZpOJT2XT78Oo1llNV1DM4G&_nc_zt=23&_nc_ht=scontent-cdg4-1.xx&_nc_gid=CUeyq4c-A9v17j3fuVA_rA&oh=00_AfiYfoaT55suJJ3-SWRXbcqEb0EK_IVBJZzexWq_GN2hAg&oe=690E5FDC" 
                    alt="Portrait de Mariano 'Manuel' Perez"
                    className="w-full max-w-3xl mx-auto rounded-lg shadow-lg border border-white/10"
                />
                <figcaption className="mt-3 text-center text-sm text-slate-400 italic max-w-2xl mx-auto">
                    Mariano "Manuel" Perez (1898-1979).
                </figcaption>
            </figure>

            <div className="prose-custom text-slate-300 max-w-none space-y-4 text-lg leading-relaxed">
                <p>On l’a longtemps appelé « el viejo de los Granadinos », le vieux de la Calle de los Granadinos, à Zuhéros Bajo. Pour beaucoup de ses contemporains, Mariano Perez n’était plus, à la fin de sa vie, qu’un vieil homme qui sortait rarement, qui allait presque toujours au même endroit – le cimetière – et dont on savait vaguement qu’il avait été maire « à une certaine époque ». Ce n’est qu’après coup, à la lumière des archives et du travail d’historiens comme Velez, que sa trajectoire est apparue pour ce qu’elle est : celle d’un homme profondément meurtri, qui a tenté, avec les moyens du bord, de sauver un village qu’il savait condamné s’il ne s’ouvrait pas.</p>
                
                <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-rose-500 pt-6 border-t border-slate-800 tracking-tight !mt-10">Un Enfant des Guerres</h3>
                <p>Mariano Perez naît à Zuhéros en 1898, dans une famille FHZ marquée par la tradition, mais aussi par une certaine sensibilité sociale. Très tôt, la mort s’invite dans sa vie. Son père et plusieurs de ses oncles partent pour les guerres du début du XXᵉ siècle : d’abord 1898, puis la guerre du Rif. Ils ne reviennent pas tous. Son grand-père, lui, sera exécuté pendant la guerre civile. Mariano se définit lui-même, dans ses mémoires, comme « le fils d’une veuve » puis « le petit-fils d’une veuve ». Toute son enfance se déroule dans des maisons où les hommes manquent, où les voix graves se font rares, où les discussions tournent autour des lettres jamais arrivées et des uniformes soigneusement pliés au fond des armoires.</p>
                <p>Une anecdote, qu’il raconte dans ses notes, résume à la fois l’absurdité de cette époque et la dureté qui s’est imprimée en lui. Un jour, pendant la guerre du Rif, des officiers viennent au village pour annoncer la mort d’un soldat – un jeune Jalfón, dont la maison se trouve juste en face de celle des Perez. Les officiers se trompent de porte et frappent chez son grand-père. L’un d’eux commence la formule rituelle : « Nous avons le regret de vous annoncer… » Le vieil homme l’interrompt net : « Désolé, il n’y a plus rien à annoncer par ici. » Tout a déjà été pris. Il n’y a plus de fils à perdre. Mariano, enfant, assiste à la scène ; elle restera gravée en lui.</p>

                <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-rose-500 pt-6 border-t border-slate-800 tracking-tight !mt-10">Le Maire Improbable</h3>
                <p>Cette expérience de la perte générationnelle façonne sa vision politique. Pendant la République, il se rapproche de la gauche, sans jamais devenir un militant de premier plan. Dans certaines versions locales, on l’appelle « Mariano » ou « Manuel » Perez, communiste ou socialiste selon les récits ; ce qu’on sait avec certitude, c’est qu’il se tient du côté de ceux qui refusent la résignation. Il survit à la guerre civile, ce qui n’est pas le cas de nombreux Zuhérois engagés à gauche. Cela ne l’épargne pas : il vit dans sa chair la peur, la clandestinité, la violence, la perte presque totale de sa branche paternelle.</p>
                <p>Après 1939, le village est exsangue. Les chiffres sont brutaux : près de 500 morts pour les seules guerres du Rif et civile, plus les invalides, les disparus, les traumatisés. Zuhéros est un village de veuves, d’orphelins, de vieux. Les hommes en âge de fonder une famille se comptent. Mariano, de son propre aveu, ne se marie jamais parce qu’« il n’y avait plus d’hommes autour de [lui] pour [lui] donner l’exemple » et parce que, pour lui, l’idée de fonder une famille dans ce paysage d’absence était presque obscène. Il ne mettra jamais d’enfants au monde, mais il va tenter de sauver ceux des autres.</p>
                <p>C’est dans ce contexte qu’il devient, dans les années 40–50, maire de Zuhéros, à un moment où la localité est officiellement constituée en commune. Son élection surprend : lui, ancien républicain, n’aurait jamais dû passer à travers les mailles du filet franquiste. Velez explique que cela tient à deux phénomènes : d’une part, une dépolitisation profonde du village, fatigué des affrontements ; d’autre part, un certain pragmatisme des autorités locales, qui voient en lui un homme travailleur, lettré, capable de négocier avec l’administration provinciale.</p>

                <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-rose-500 pt-6 border-t border-slate-800 tracking-tight !mt-10">Ouvrir pour Survivre</h3>
                <p>Là où Mariano Perez se distingue vraiment, c’est par son choix d’ouvrir Zuhéros à des familles venues de l’extérieur – ce que l’on appellera plus tard les FNZ. Dans ses mémoires, il note :</p>
                <blockquote className="relative my-6 pl-6 text-slate-200 italic before:absolute before:left-0 before:top-0 before:h-full before:w-1 before:bg-gradient-to-b before:from-blue-500 before:to-rose-600 rounded">
                « Bien sûr, qu’ils m’en voudront, écrivait-il. Mais je voyais ce que le village était après la guerre, en arpentant ses rues, en parlant à ses habitants, qui étaient mes voisins, mes cousins, mes cousins éloignés. Je l’ai vécu dans ma chair : mes oncles et mon père morts au Maroc, mon grand-père assassiné pendant la guerre civile. J’ai été le fils d’une veuve, le petit-fils d’une veuve. Ma branche maternelle, plus chanceuse, comptait des survivants, des handicapés, des disparus, mais pas de morts enterrés. Il fallait ouvrir Zuhéros à de nouveaux horizons plutôt que de le laisser devenir un amas de ruines croulant sous le poids de l’âge de ses habitants et de l’émigration de ses éléments productifs. La capacité juvénile zuhéroise ne permettait plus de tenir une dynamique de croissance. »
                </blockquote>
                <p>Cette lucidité démographique le met en porte-à-faux avec une partie des FHZ, qui le considèrent comme un « fossoyeur » de l’identitaire. En réalité, il fait le calcul inverse : pour lui, sans arrivants, le village est condamné à mourir physiquement – maisons vides, commerces fermés, terres en friche. Les FNZ qui s’installent tiennent les commerces FHZ, entretiennent les terres FHZ, payent des loyers aux propriétaires FHZ qui ont hérité de leurs parents ou de leurs oncles tués ou exilés. Mariano Perez voit dans cette cohabitation une manière de prolonger, même de façon détournée, la présence des familles fondatrices.</p>
                <p>« Quand les biens ont pris de la valeur, écrira-t-il encore, les FHZ se sont enrichis, embourgeoisés. Mais c’était aussi la réussite des FNZ. Je ne suis pas du même bord politique que beaucoup d’entre eux, mais pour une fois nous allions dans le même sens : empêcher Zuhéros de devenir un cimetière habité par des pierres. »</p>

                <h3 className="text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-rose-500 pt-6 border-t border-slate-800 tracking-tight !mt-10">Une Fin de Vie Solitaire</h3>
                <p>L’histoire ne lui rend pas justice de son vivant. Certains FHZ issus des familles fondatrices le détestent, d’autres l’ignorent, pour beaucoup il n’est plus que « le vieux de l’immeuble », celui qui descend rarement, qui va au cimetière, qui ne se mêle plus aux conversations de la Plaza. Il finit sa vie dans un modeste appartement de la Calle de los Granadinos, entouré de vêtements qui ne sont pas tous les siens : chemises, vestes, pantalons, cravates, chapeaux de son père et de ses oncles, morts jeunes. Il raconte qu’entre 1921 et 1927, son grand-père a refait cinq fois son testament, parce qu’il perdait ses fils les uns après les autres. « Pendant des années, je n’ai presque plus acheté d’habits, confie-t-il à Velez. Il restait tellement des leurs que je portais les vêtements des morts. »</p>
                <p>Lorsque l’historien Velez vient l’interviewer, dans les années 1970, il trouve un homme profondément meurtri, mais d’une lucidité intacte. Par moments, Mariano a les larmes aux yeux, puis s’excuse : « Désolé, ce n’est plus l’âge. » Ils parlent des guerres, des familles décimées, des rues vidées après le Rif et la guerre civile, de ce CFHZ qui, à l’origine, assistait les familles précarisées par les conflits. Ils parlent aussi de la décision d’ouvrir les portes du village. Pour Velez, il est clair que Mariano Perez a payé de sa réputation ce choix stratégique.</p>
                <p>Il meurt en 1979, dans la solitude relative de son appartement. Il n’a ni femme, ni enfants, ni grande cérémonie. Quelques proches, quelques anciens, quelques fonctionnaires assistent à l’enterrement. Beaucoup d’habitants de Zuhéros ne savent pas vraiment qui il était. Certains, parmi les FHZ, garderont longtemps rancœur contre lui. D’autres, plus jeunes, le réduiront à une silhouette : « le vieux qui allait au cimetière ».</p>
                <p>Ce n’est que plus tard, quand on superpose les courbes démographiques et les décisions politiques, qu’apparaît la portée de son action. Sans l’arrivée progressive des FNZ dans les années 50–70, sans les autorisations de permis, les ventes de parcelles, les adaptations d’infrastructures qu’il a soutenues ou initiées, Zuhéros serait probablement devenu ce qu’il redoutait : un village-musée presque vide, avec quelques vieilles familles fossilisées. Au lieu de cela, il est devenu une petite ville qui s’étend, certes au prix d’une dilution de la présence FHZ, mais en évitant la disparition pure et simple.</p>
                <blockquote className="relative my-6 pl-6 text-slate-200 italic before:absolute before:left-0 before:top-0 before:h-full before:w-1 before:bg-gradient-to-b before:from-blue-500 before:to-rose-600 rounded">
                Velez le résume d’une formule : « Mariano Perez est un homme à qui l’histoire n’a pas rendu justice. Ce n’était pas un visionnaire au sens héroïque, c’était un survivant qui voyait ce que les autres refusaient de regarder. Il avait compris que Zuhéros avait déjà perdu trop d’hommes pour se permettre de perdre en plus l’avenir. »
                </blockquote>
                <p>Aujourd’hui, lorsque l’on regarde les chiffres, lorsque l’on constate que les FHZ ne représentent plus qu’une petite minorité vieillissante, on peut débattre à l’infini de ses choix. Mais une chose apparaît clairement : Mariano Perez a incarné, à son époque, une forme de courage discret. Celui de dire à son propre camp ce qu’il n’avait aucune envie d’entendre : qu’un village ne se sauve pas seulement avec la mémoire, mais aussi avec des naissances, des arrivées, des commerces ouverts, des écoles pleines. Qu’il ne suffit pas de pleurer les morts ; il faut aussi organiser la survie.</p>
            </div>
        </>
    );
};

export default MarianoPerezPage;
